In [6]:
import pandas as pd 
import numpy as np 
import datetime as dt

Create a Pandas Series of 5 random date strings in the format 'DD-MM-YYYY', then convert this Series to datetime objects using pd.to_datetime and print the result.

In [2]:
date_strings = pd.Series([
    '15-01-2024',
    '22-03-2024',
    '05-07-2024',
    '18-09-2024',
    '30-11-2024'
])

result = pd.to_datetime(date_strings,format='%d-%m-%Y')
result

0   2024-01-15
1   2024-03-22
2   2024-07-05
3   2024-09-18
4   2024-11-30
dtype: datetime64[us]

Given a DataFrame with a 'release_date' column containing movie release dates (as strings), add three new columns: 'year', 'month', and 'day' by extracting these values from the 'release_date' column using Pandas.<br><br><em><strong>Hint:</strong> Use the .dt accessor after converting to datetime.</em>

In [3]:
data = {
    'movie_title': [
        'Avatar: The Way of Water',
        'Oppenheimer',
        'Barbie',
        'Dune: Part Two',
        'Inside Out 2'
    ],
    'release_date': [
        '16-12-2022',
        '21-07-2023',
        '21-07-2023',
        '01-03-2024',
        '14-06-2024'
    ]
}

df = pd.DataFrame(data)

df['release_date'] = pd.to_datetime(df['release_date'],dayfirst=True)

df['day'] = df['release_date'].dt.day
df['month'] = df['release_date'].dt.month
df['year'] = df['release_date'].dt.year

df

                movie_title release_date  day  month  year
0  Avatar: The Way of Water   2022-12-16   16     12  2022
1               Oppenheimer   2023-07-21   21      7  2023
2                    Barbie   2023-07-21   21      7  2023
3            Dune: Part Two   2024-03-01    1      3  2024
4              Inside Out 2   2024-06-14   14      6  2024

Generate a date range for the next 7 days starting from today using pd.date_range, and display the list of dates in the console.

In [4]:
result = pd.date_range(start='01-10-2026',periods=7)
result

DatetimeIndex(['2026-01-10', '2026-01-11', '2026-01-12', '2026-01-13',
               '2026-01-14', '2026-01-15', '2026-01-16'],
              dtype='datetime64[us]', freq='D')

Suppose you have a DataFrame of Zomato Gold subscriptions with columns 'user_id' and 'start_date' (as strings). Calculate the tenure (in days) for each user by subtracting the 'start_date' from today's date, and add it as a new column 'tenure_days'.<br><br><em><strong>Hint:</strong> Use pd.to_datetime for conversion and (today - start_date).dt.days for calculation.</em>

In [16]:
data = {
    'user_id': [101, 102, 103, 104, 105],
    'start_date': ['15-01-2023', '01-06-2023', '10-12-2023', '20-03-2024', '05-08-2024']
}

df = pd.DataFrame(data)
df['start_date'] = pd.to_datetime(date_strings,format='%d-%m-%Y')
df['tenure_days'] = (pd.to_datetime(dt.date.today()) - df['start_date'])
df

   user_id start_date tenure_days
0      101 2024-01-15   1002 days
1      102 2024-03-22    935 days
2      103 2024-07-05    830 days
3      104 2024-09-18    755 days
4      105 2024-11-30    682 days