In [9]:
import pandas as pd

Download a CSV file of IPL match results from Kaggle or any open dataset, then use pandas read_csv() to load it into a DataFrame and display the first 10 rows using head().

In [15]:
df = pd.read_csv("C:/Users/lenovo/Desktop/Assignments/Datasaets/IPL_Ball_by_Ball_2022.csv")
# df.head(10)
df_1 = df.head(20)
df_1

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
5,1312200,1,0,6,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
6,1312200,1,1,1,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
7,1312200,1,1,2,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
8,1312200,1,1,3,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
9,1312200,1,1,4,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
10,1312200,1,1,5,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
11,1312200,1,1,6,YBK Jaiswal,Yash Dayal,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
12,1312200,1,2,1,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
13,1312200,1,2,2,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
14,1312200,1,2,3,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,4,0,4,0,0,NaN,NaN,NaN,Rajasthan Royals
15,1312200,1,2,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
16,1312200,1,2,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,6,0,6,0,0,NaN,NaN,NaN,Rajasthan Royals
17,1312200,1,2,6,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,3,0,3,0,0,NaN,NaN,NaN,Rajasthan Royals
18,1312200,1,3,1,YBK Jaiswal,Yash Dayal,JC Buttler,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
19,1312200,1,3,2,JC Buttler,Yash Dayal,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals

Find a small Excel file of your own mobile expenses (or create one with 5-10 rows), then use pandas read_excel() to load it and print the last 3 rows using tail().

In [11]:
# ! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [12]:
df1 = pd.read_excel("C:/Users/lenovo/Desktop/Assignments/Datasaets/Mobile_expences.xlsx")
df1.tail(3)

        Date  Category          Description  Amount (₹)
7 2026-09-08  Recharge         Monthly plan         349
8 2026-09-09      Data  Extra internet data          79
9 2026-09-10       SMS             SMS pack          29

Use describe() and info() on a DataFrame loaded from a Zomato restaurant dataset (or any food delivery data you can find online), and write down 2 insights about the data (for example: number of restaurants, missing values, or average ratings).<br><br><em><strong>Hint:</strong> Focus on what info() and describe() reveal about columns and data types.</em>

In [13]:
df2 = pd.read_csv("C:/Users/lenovo/Desktop/Assignments/Datasaets/Zomato-data-.csv")
df2.info()
df2.describe()

#insights 
#There are no missing values in data set.
#Average cost for two people to eat is 418.

<class 'pandas.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    str
 1   online_order                 148 non-null    str
 2   book_table                   148 non-null    str
 3   rate                         148 non-null    str
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    str
dtypes: int64(2), str(5)
memory usage: 12.7 KB

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

Export the DataFrame from your IPL or food delivery dataset to a new CSV file called 'filtered_data.csv', but only include the first 20 rows.

In [16]:
df_1.to_csv('C:/Users/lenovo/Desktop/Assignments/Datasaets/filtered_data.csv')

Load any dataset of your choice (not the one used in the class demo), and export it to Excel format with a custom sheet name like 'Analysis2024'.<br><br><em><strong>Constraint:</strong> Use the to_excel() method and set the sheet_name parameter.</em>

In [18]:
data = pd.read_excel("C:/Users/lenovo/Desktop/Assignments/Datasaets/Mobile_expences.xlsx")
data.to_excel("C:/Users/lenovo/Desktop/Assignments/Datasaets/Analysis2024.xlsx")
print("done..................")

done..................